name: 'PR description checker'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled
jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jadrol/pr-description-checker-action@489a3f3d076fad4d8e87b346916fb7bd612cdd04 # v1.3.0
        id: description-checker
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
